# ---------- BUILD STAGE ----------
FROM node:20-alpine

WORKDIR /app

# Copy package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

#Expose Vite port 
EXPOSE 5173

CMD ["npm", "run", "dev"]
