-- Seed data for TarrificDB
-- Generated by SeedDataGenerator.java
-- Passwords are BCrypt-hashed for security
-- All INSERT statements are idempotent (can re-run)

USE TarrificDB;

-- ========== User Accounts ==========
-- one for each grpmate w BCrypt-hashed passwords

INSERT INTO account (email, password, username)
SELECT 'rachel@tarrific.com', '$2a$10$kGn2wEaUOraL9Wc6e8xA6ec31RlTMLinCJvEU0L0NodsVenOkGJkK', 'rachel' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = 'rachel@tarrific.com');

INSERT INTO account (email, password, username)
SELECT 'elodie@tarrific.com', '$2a$10$LN.6wAnesVBQB8fpLrSI7eo0KD/jBPZhYn/EVsneNYW7sZxemn13W', 'elodie' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = 'elodie@tarrific.com');

INSERT INTO account (email, password, username)
SELECT 'xinyu@tarrific.com', '$2a$10$dnKZl1mu8uPdZekYdN93lOiL2lzVRcVQ2ObyRP9GqMVC3RHkSZYg6', 'xinyu' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = 'xinyu@tarrific.com');

INSERT INTO account (email, password, username)
SELECT 'amos@tarrific.com', '$2a$10$nEMYPYTAfZgw.Se7mJ4oVe9QKx9DkXocBFRdwBgItAzCYubdI5LBW', 'amos' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = 'amos@tarrific.com');

INSERT INTO account (email, password, username)
SELECT 'roopa@tarrific.com', '$2a$10$wH00P7IVJIt0mpb1TLaiLOKM06plA.hlrpoQbp3j32DJgZe7ktlbm', 'roopa' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = 'roopa@tarrific.com');

INSERT INTO account (email, password, username)
SELECT 'jordan@tarrific.com', '$2a$10$igZWvdW.vfsUQCjZmRiv3e/Owqrm68fP.Cz0RSkINKKE8PHK2FanK', 'jordan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = 'jordan@tarrific.com');

-- 
-- ========== Historical User Queries ==========
-- Past tariff queries made by users for analytics and history
-- Note: Query entity has @ManyToOne relationship with Account
-- The foreign key column name is 'userID' (mapped from Account entity)

INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)
VALUES ('8471.30.0100', 'SEA', 'CHINA', 100, 1);

INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)
VALUES ('8528.72.6400', 'AIR', 'JAPAN', 50, 1);

INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)
VALUES ('9503.00.0073', 'SEA', 'VIETNAM', 200, 2);

INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)
VALUES ('6109.10.0012', 'SEA', 'BANGLADESH', 500, 2);

INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)
VALUES ('8471.30.0100', 'AIR', 'TAIWAN', 75, 1);

-- Seed data generation complete
