package app.query;

import java.util.Map;
import java.util.HashMap;

public class CountryCodes {
    public static Map<String, String> isoCountryMap = new HashMap<>() {
        {
            put("Afghanistan", "AF");
            put("Albania", "AL");
            put("Algeria", "DZ");
            put("American Samoa", "AS");
            put("Andorra", "AD");
            put("Angola", "AO");
            put("Anguilla", "AI");
            put("Antarctica", "AQ");
            put("Antigua and Barbuda", "AG");
            put("Argentina", "AR");
            put("Armenia", "AM");
            put("Aruba", "AW");
            put("Australia", "AU");
            put("Austria", "AT");
            put("Azerbaijan", "AZ");
            put("Bahamas", "BS");
            put("Bahrain", "BH");
            put("Bangladesh", "BD");
            put("Barbados", "BB");
            put("Belarus", "BY");
            put("Belgium", "BE");
            put("Belize", "BZ");
            put("Benin", "BJ");
            put("Bermuda", "BM");
            put("Bhutan", "BT");
            put("Bolivia", "BO");
            put("Bosnia and Herzegovina", "BA");
            put("Botswana", "BW");
            put("Brazil", "BR");
            put("British Indian Ocean Territory", "IO");
            put("British Virgin Islands", "VG");
            put("Brunei Darussalam", "BN");
            put("Bulgaria", "BG");
            put("Burkina Faso", "BF");
            put("Burundi", "BI");
            put("Cambodia", "KH");
            put("Cameroon", "CM");
            put("Canada", "CA");
            put("Cape Verde", "CV");
            put("Cayman Islands", "KY");
            put("Central African Republic", "CF");
            put("Chad", "TD");
            put("Chile", "CL");
            put("China", "CN");
            put("Christmas Island", "CX");
            put("Cocos (Keeling) Islands", "CC");
            put("Colombia", "CO");
            put("Comoros", "KM");
            put("Congo, Democratic Republic of the", "CD");
            put("Congo, Republic of the", "CG");
            put("Cook Islands", "CK");
            put("Costa Rica", "CR");
            put("Côte d'Ivoire", "CI");
            put("Croatia", "HR");
            put("Cuba", "CU");
            put("Cyprus", "CY");
            put("Czech Republic", "CZ");
            put("Denmark", "DK");
            put("Djibouti", "DJ");
            put("Dominica", "DM");
            put("Dominican Republic", "DO");
            put("Ecuador", "EC");
            put("Egypt", "EG");
            put("El Salvador", "SV");
            put("Equatorial Guinea", "GQ");
            put("Eritrea", "ER");
            put("Estonia", "EE");
            put("Ethiopia", "ET");
            put("Falkland Islands (Malvinas)", "FK");
            put("Faroe Islands", "FO");
            put("Fiji", "FJ");
            put("Finland", "FI");
            put("France", "FR");
            put("French Guiana", "GF");
            put("French Polynesia", "PF");
            put("Gabon", "GA");
            put("Gambia", "GM");
            put("Georgia", "GE");
            put("Germany", "DE");
            put("Ghana", "GH");
            put("Gibraltar", "GI");
            put("Greece", "GR");
            put("Greenland", "GL");
            put("Grenada", "GD");
            put("Guadeloupe", "GP");
            put("Guam", "GU");
            put("Guatemala", "GT");
            put("Guernsey", "GG");
            put("Guinea", "GN");
            put("Guinea-Bissau", "GW");
            put("Guyana", "GY");
            put("Haiti", "HT");
            put("Honduras", "HN");
            put("Hong Kong", "HK");
            put("Hungary", "HU");
            put("Iceland", "IS");
            put("India", "IN");
            put("Indonesia", "ID");
            put("Iran", "IR");
            put("Iraq", "IQ");
            put("Ireland", "IE");
            put("Isle of Man", "IM");
            put("Israel", "IL");
            put("Italy", "IT");
            put("Jamaica", "JM");
            put("Japan", "JP");
            put("Jersey", "JE");
            put("Jordan", "JO");
            put("Kazakhstan", "KZ");
            put("Kenya", "KE");
            put("Kiribati", "KI");
            put("Korea, Republic of", "KR");
            put("Kuwait", "KW");
            put("Kyrgyzstan", "KG");
            put("Lao People's Democratic Republic", "LA");
            put("Latvia", "LV");
            put("Lebanon", "LB");
            put("Lesotho", "LS");
            put("Liberia", "LR");
            put("Libya", "LY");
            put("Liechtenstein", "LI");
            put("Lithuania", "LT");
            put("Luxembourg", "LU");
            put("Macao", "MO");
            put("North Macedonia", "MK");
            put("Madagascar", "MG");
            put("Malawi", "MW");
            put("Malaysia", "MY");
            put("Maldives", "MV");
            put("Mali", "ML");
            put("Malta", "MT");
            put("Marshall Islands", "MH");
            put("Martinique", "MQ");
            put("Mauritania", "MR");
            put("Mauritius", "MU");
            put("Mayotte", "YT");
            put("Mexico", "MX");
            put("Micronesia, Federated States of", "FM");
            put("Moldova, Republic of", "MD");
            put("Monaco", "MC");
            put("Mongolia", "MN");
            put("Montenegro", "ME");
            put("Montserrat", "MS");
            put("Morocco", "MA");
            put("Mozambique", "MZ");
            put("Myanmar", "MM");
            put("Namibia", "NA");
            put("Nauru", "NR");
            put("Nepal", "NP");
            put("Netherlands", "NL");
            put("New Caledonia", "NC");
            put("New Zealand", "NZ");
            put("Nicaragua", "NI");
            put("Niger", "NE");
            put("Nigeria", "NG");
            put("Niue", "NU");
            put("Norfolk Island", "NF");
            put("Northern Mariana Islands", "MP");
            put("Norway", "NO");
            put("Oman", "OM");
            put("Pakistan", "PK");
            put("Palau", "PW");
            put("Panama", "PA");
            put("Papua New Guinea", "PG");
            put("Paraguay", "PY");
            put("Peru", "PE");
            put("Philippines", "PH");
            put("Pitcairn", "PN");
            put("Poland", "PL");
            put("Portugal", "PT");
            put("Puerto Rico", "PR");
            put("Qatar", "QA");
            put("Romania", "RO");
            put("Russian Federation", "RU");
            put("Rwanda", "RW");
            put("Réunion", "RE");
            put("Saint Barthélemy", "BL");
            put("Saint Helena, Ascension and Tristan da Cunha", "SH");
            put("Saint Kitts and Nevis", "KN");
            put("Saint Lucia", "LC");
            put("Saint Martin (French part)", "MF");
            put("Saint Pierre and Miquelon", "PM");
            put("Saint Vincent and the Grenadines", "VC");
            put("Samoa", "WS");
            put("San Marino", "SM");
            put("Sao Tome and Principe", "ST");
            put("Saudi Arabia", "SA");
            put("Senegal", "SN");
            put("Serbia", "RS");
            put("Seychelles", "SC");
            put("Sierra Leone", "SL");
            put("Singapore", "SG");
            put("Sint Maarten (Dutch part)", "SX");
            put("Slovakia", "SK");
            put("Slovenia", "SI");
            put("Solomon Islands", "SB");
            put("Somalia", "SO");
            put("South Africa", "ZA");
            put("South Sudan", "SS");
            put("Spain", "ES");
            put("Sri Lanka", "LK");
            put("Sudan", "SD");
            put("Suriname", "SR");
            put("Sweden", "SE");
            put("Switzerland", "CH");
            put("Syrian Arab Republic", "SY");
            put("Taiwan, Province of China", "TW");
            put("Tajikistan", "TJ");
            put("Tanzania, United Republic of", "TZ");
            put("Thailand", "TH");
            put("Timor-Leste", "TL");
            put("Togo", "TG");
            put("Tokelau", "TK");
            put("Tonga", "TO");
            put("Trinidad and Tobago", "TT");
            put("Tunisia", "TN");
            put("Turkey", "TR");
            put("Turkmenistan", "TM");
            put("Turks and Caicos Islands", "TC");
            put("Tuvalu", "TV");
            put("Uganda", "UG");
            put("Ukraine", "UA");
            put("United Arab Emirates", "AE");
            put("United Kingdom", "GB");
            put("United States", "US");
            put("United States Minor Outlying Islands", "UM");
            put("Uruguay", "UY");
            put("Uzbekistan", "UZ");
            put("Vanuatu", "VU");
            put("Venezuela", "VE");
            put("Viet Nam", "VN");
            put("Western Sahara", "EH");
            put("Yemen", "YE");
            put("Zambia", "ZM");
            put("Zimbabwe", "ZW");
        }
    };
}
