### Test US HTS REST API search endpoint

# Search for tariff articles containing the word "petroleum"
# GET http://localhost:8080/api/tariffs/search?keyword=sugar


# idk



# Search for tariff articles containing the word "sugar" and compare countries
GET http://localhost:8080/api/tariffs/compare-countries?htsno=2710.12.15&keyword=motor

Accept: application/json

###
GET http://localhost:8080/api/tariffs/most-queried
Accept: application/json