package app.utility;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Utility class to generate seed-data.sql with BCrypt-hashed passwords.
 * 
 * - Generates idempotent SQL INSERT statements (won't create duplicates if run multiple times)
 * - Outputs to seed-data.sql file that can be used by MySQL init scripts
 * 
 * HOW TO USE:
 * 1. Run this class as a Java application (right-click -> Run 'SeedDataGenerator.main()')
 * 2. It will create/overwrite backend/seed-data.sql
 * 3. The generated SQL file will be picked up by init.sql on next Docker restart
 * 
 * WHY BCRYPT:
 * - BCrypt is a one-way hash function designed for passwords
 * - It includes a salt (random data) automatically to prevent rainbow table attacks
 * - The "10" parameter is the cost factor (higher = slower but more secure)
 * - Your app uses BCrypt, so seed data must also use BCrypt for login to work
 */
public class SeedDataGenerator {

    public static void main(String[] args) {
        // BCrypt encoder with cost factor 10 (same as your app's SecurityConfig likely uses)
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(10);
        
        // Output file path (relative to backend directory)
        String outputPath = "seed-data.sql";
        
        try (PrintWriter writer = new PrintWriter(new FileWriter(outputPath))) {
            
            // SQL file header
            writer.println("-- Seed data for TarrificDB");
            writer.println("-- Generated by SeedDataGenerator.java");
            writer.println("-- Passwords are BCrypt-hashed for security");
            writer.println("-- All INSERT statements are idempotent (safe to re-run)");
            writer.println();
            writer.println("USE TarrificDB;");
            writer.println();
            
            // ========== SEED ACCOUNTS ==========
            writer.println("-- ========== User Accounts ==========");
            writer.println("-- These accounts represent your team members with BCrypt-hashed passwords");
            writer.println();
            
            // Define users: email, plaintext password, username
            String[][] users = {
                {"admin@tarrific.com", "PasswordAdmin12345!", "admin"},
                {"rachel@tarrific.com", "PasswordRachel12345!", "rachel"},
                {"elodie@tarrific.com", "PasswordElodie12345!", "elodie"},
                {"xinyu@tarrific.com", "PasswordXinyu12345!", "xinyu"},
                {"amos@tarrific.com", "PasswordAmos12345!", "amos"},
                {"roopa@tarrific.com", "PasswordRoopa12345!", "roopa"},
                {"jordan@tarrific.com", "PasswordJordan12345!", "jordan"}
            };
            
            // Generate INSERT for each user
            for (String[] user : users) {
                String email = user[0];
                String plaintextPassword = user[1];
                String username = user[2];
                
                // Hash the password using BCrypt
                String hashedPassword = encoder.encode(plaintextPassword);
                
                // Generate idempotent INSERT (only inserts if email doesn't exist)
                // This prevents duplicate entries if script runs multiple times
                writer.println("INSERT INTO account (email, password, username)");
                writer.println("SELECT '" + email + "', '" + hashedPassword + "', '" + username + "' FROM DUAL");
                writer.println("WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = '" + email + "');");
                writer.println();
            }
        
            
            // ========== SEED HISTORICAL QUERIES ==========
            writer.println("-- ========== Historical User Queries ==========");
            writer.println("-- Past tariff queries made by users for analytics (world map + line graph)");
            writer.println("-- Note: Query entity has @ManyToOne relationship with Account");
            writer.println("-- The foreign key column name is 'userID' (mapped from Account entity)");
            writer.println();
            
            // Define historical queries: only hts_code and userid matter now
            // Format: {hts_code, userid}
            String[][] queries = {
                // Multiple queries for same HTS code for top10queries
                {"0404.90.10.00", "1"}, 
                {"0404.90.10.00", "1"}, 
                {"0404.90.10.00", "1"}, 
                {"0404.90.10.00", "1"}, 
                {"0404.90.10.00", "1"}, 
                {"0404.90.10.00", "1"}, 

                {"2303.20.00.00", "3"},
                {"2303.20.00.00", "3"},
                {"2303.20.00.00", "3"},
                {"2303.20.00.00", "3"},
                {"2303.20.00.00", "3"},

                {"1905.90.10.70", "2"},
                {"1905.90.10.70", "2"},
                {"1905.90.10.70", "2"},
                {"1905.90.10.70", "2"},
 

                // ===== Product Categories =====
                
                // Egg Products
                {"0408.11.00.00", "1"},
                {"0408.19.00.00", "2"},
                {"0408.91.00.00", "2"},
                {"0408.99.00.00", "2"},

                // Rice Products
                {"1006.10.00.00", "1"},
                {"1006.20.20.10", "1"},
                {"1006.20.20.90", "1"},
                {"1006.20.40.25", "1"},
                {"1006.20.40.35", "1"},
                {"1006.20.40.40", "1"},
                {"1006.20.40.60", "1"},
                {"1006.20.40.80", "1"},
                {"1006.30.10.20", "1"},
                {"1006.30.10.40", "1"},
                {"1006.30.90.15", "1"},
                {"1006.30.90.57", "1"},
                {"1006.30.90.59", "1"},
                {"1006.30.90.61", "1"},
                {"1006.30.90.65", "1"},
                {"1006.30.90.75", "1"},
                {"1006.40.00.00", "1"},

                // Milk Products (not concentrated 0401)
                {"0401.10.00.00", "2"},
                {"0401.20.20.00", "2"},
                {"0401.20.40.00", "2"},
                {"0401.40.02.00", "2"},
                {"0401.40.05.00", "2"},
                {"0401.40.25.00", "3"},
                {"0401.50.02.00", "3"},
                {"0401.50.05.00", "3"},
                {"0401.50.25.00", "3"},
                {"0401.50.42.00", "3"},
                {"0401.50.50.00", "4"},
                {"0401.50.75.00", "4"},

                // Milk Products (concentrated 0402)
                {"0402.10.05.00", "4"},
                {"0402.10.10.00", "4"},
                {"0402.10.10.50", "4"},
                {"0402.21.02.00", "4"},
                {"0402.21.05.00", "5"},
                {"0402.21.25.00", "5"},
                {"0402.21.27.00", "5"},
                {"0402.21.30.00", "5"},
                {"0402.21.50.00", "5"},
                {"0402.21.73.00", "5"},
                {"0402.21.75.00", "5"},
                {"0402.21.90.00", "5"},
                {"0402.29.05.00", "5"},
                {"0402.29.10.00", "5"},
                {"0402.29.50.00", "5"},
                {"0402.91.03.00", "5"},
                {"0402.91.06.00", "5"},
                {"0402.91.10.00", "5"},
                {"0402.91.30.00", "6"},
                {"0402.91.70.00", "6"},
                {"0402.91.90.00", "6"},
                {"0402.99.03.00", "6"},
                {"0402.99.06.00", "6"},
                {"0402.99.10.00", "6"},
                {"0402.99.30.00", "6"},
                {"0402.99.45.00", "6"},
                {"0402.99.55.00", "6"},
                {"0402.99.68.00", "6"},
                {"0402.99.70.00", "6"},
                {"0402.99.90.00", "6"},

                // Bread Products
                {"1905.10.00.00", "1"},
                {"1905.20.00.00", "1"},
                {"1905.31.00.21", "1"},
                {"1905.31.00.29", "1"},
                {"1905.31.00.41", "2"},
                {"1905.31.00.49", "2"},
                {"1905.32.00.21", "2"},
                {"1905.32.00.29", "2"},
                {"1905.32.00.41", "2"},
                {"1905.32.00.49", "2"},
                {"1905.40.00.00", "2"},
                {"1905.90.10.41", "2"},
                {"1905.90.10.49", "2"},
                {"1905.90.10.50", "2"},
                {"1905.90.10.70", "2"},
                {"1905.90.10.90", "2"},
                {"1905.90.90.30", "3"},
                {"1905.90.90.60", "3"},
                {"1905.90.90.90", "3"},

                // Sugar Products
                {"2303.20.00.00", "3"},
                {"0403.90.85.00", "3"},
                {"1701.14.20.00", "3"},
                {"1701.91.52.00", "3"},
                {"1701.13.20.00", "3"},
                {"1701.91.42.00", "3"},
                {"1702.90.05.00", "3"},
                {"1702.40.28.00", "3"},
                {"1702.60.28.00", "3"},
                {"1702.90.58.00", "3"},
                {"1702.90.10.00", "4"},
                {"1702.90.64.00", "4"},
                {"1702.20.28", "4"},
                {"1702.30.28.00", "4"},
                {"2202.99.10.00", "4"},
                {"2202.10.00", "4"},
                {"0404.90.10.00", "4"},

            };
            
            for (String[] query : queries) {
                String htsCode = query[0];
                String userId = query[4];  // Keep only HTS code and userID
                
                // Use default values for other fields:
                // - mode_of_transport: "ANY" (default transport mode)
                // - origin_country: "ALL" (default country)
                // - quantity: 100 (default quantity)
                
                // No idempotency check for queries - historical records can have duplicates
                // Column name is 'userID' (not 'userid') to match JPA @JoinColumn mapping
                writer.println("INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)");
                writer.println("VALUES ('" + htsCode + "', 'ANY', 'ALL', 100, " + userId + ");");
                writer.println();
            }
            
            writer.println("-- Seed data generation complete");
            
            System.out.println("✓ Successfully generated seed-data.sql");
            System.out.println("✓ File location: backend/seed-data.sql");
            System.out.println("✓ Passwords have been BCrypt-hashed (cost factor: 10)");
            System.out.println();
            System.out.println("Next steps:");
            System.out.println("1. Review the generated seed-data.sql file");
            System.out.println("2. Ensure init.sql includes seed-data.sql (or append its contents)");
            System.out.println("3. Run: docker compose down -v");
            System.out.println("4. Run: docker compose up --build");
            System.out.println("5. Verify data: docker exec -it TarrificDB-mysql mysql -u sa -D TarrificDB -e \"SELECT * FROM account;\"");
            
        } catch (IOException e) {
            System.err.println("✗ Error generating seed-data.sql: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
