package app.utility;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Utility class to generate seed-data.sql with BCrypt-hashed passwords.
 * 
 * - Generates idempotent SQL INSERT statements (won't create duplicates if run multiple times)
 * - Outputs to seed-data.sql file that can be used by MySQL init scripts
 * 
 * HOW TO USE:
 * 1. Run this class as a Java application (right-click -> Run 'SeedDataGenerator.main()')
 * 2. It will create/overwrite backend/seed-data.sql
 * 3. The generated SQL file will be picked up by init.sql on next Docker restart
 * 
 * WHY BCRYPT:
 * - BCrypt is a one-way hash function designed for passwords
 * - It includes a salt (random data) automatically to prevent rainbow table attacks
 * - The "10" parameter is the cost factor (higher = slower but more secure)
 * - Your app uses BCrypt, so seed data must also use BCrypt for login to work
 */
public class SeedDataGenerator {

    public static void main(String[] args) {
        // BCrypt encoder with cost factor 10 (same as your app's SecurityConfig likely uses)
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(10);
        
        // Output file path (relative to backend directory)
        String outputPath = "seed-data.sql";
        
        try (PrintWriter writer = new PrintWriter(new FileWriter(outputPath))) {
            
            // SQL file header
            writer.println("-- Seed data for TarrificDB");
            writer.println("-- Generated by SeedDataGenerator.java");
            writer.println("-- Passwords are BCrypt-hashed for security");
            writer.println("-- All INSERT statements are idempotent (safe to re-run)");
            writer.println();
            writer.println("USE TarrificDB;");
            writer.println();
            
            // ========== SEED ACCOUNTS ==========
            writer.println("-- ========== User Accounts ==========");
            writer.println("-- These accounts represent your team members with BCrypt-hashed passwords");
            writer.println();
            
            // Define users: email, plaintext password, username
            String[][] users = {
                {"admin@tarrific.com", "PasswordAdmin12345!", "admin"},
                {"rachel@tarrific.com", "PasswordRachel12345!", "rachel"},
                {"elodie@tarrific.com", "PasswordElodie12345!", "elodie"},
                {"xinyu@tarrific.com", "PasswordXinyu12345!", "xinyu"},
                {"amos@tarrific.com", "PasswordAmos12345!", "amos"},
                {"roopa@tarrific.com", "PasswordRoopa12345!", "roopa"},
                {"jordan@tarrific.com", "PasswordJordan12345!", "jordan"}
            };
            
            // Generate INSERT for each user
            for (String[] user : users) {
                String email = user[0];
                String plaintextPassword = user[1];
                String username = user[2];
                
                // Hash the password using BCrypt
                String hashedPassword = encoder.encode(plaintextPassword);
                
                // Generate idempotent INSERT (only inserts if email doesn't exist)
                // This prevents duplicate entries if script runs multiple times
                writer.println("INSERT INTO account (email, password, username)");
                writer.println("SELECT '" + email + "', '" + hashedPassword + "', '" + username + "' FROM DUAL");
                writer.println("WHERE NOT EXISTS (SELECT 1 FROM account WHERE email = '" + email + "');");
                writer.println();
            }
            
            // ========== SEED FAVOURITE HTS CODES ==========
            // writer.println("-- ========== Favourite HTS Codes ==========");
            // writer.println("-- Common tariff codes that can be favourited by users");
            // writer.println();
            
            // String[] htsCodes = {
            //     // "", // add in codes of fav hts in the brackets
            // };
            
            // for (String code : htsCodes) {
            //     writer.println("INSERT INTO favourite_hts_codes (hts_code)");
            //     writer.println("SELECT '" + code + "' FROM DUAL");
            //     writer.println("WHERE NOT EXISTS (SELECT 1 FROM favourite_hts_codes WHERE hts_code = '" + code + "');");
            //     writer.println();
            // }
            
            // // ========== LINK FAVOURITES TO ACCOUNTS ==========
            // writer.println("-- ========== Link Favourites to User Accounts ==========");
            // writer.println("-- Associates HTS codes with user accounts");
            // writer.println("-- Note: userid 1 = rachel, 2 = elodie, etc. (based on insertion order above)");
            // writer.println();
            
            // // Map account ID to HTS codes
            // // IMPORTANT: Account IDs are auto-increment, so first inserted user gets ID 1
            // String[][] favouriteLinks = {
            //     {"1", "8471.30.0100"},  // Rachel's favourites
            //     {"1", "8528.72.6400"},
            //     {"2", "9503.00.0073"},  // Elodie's favourites
            //     {"2", "6109.10.0012"}
            // };
            
            // for (String[] link : favouriteLinks) {
            //     String accountId = link[0];
            //     String htsCode = link[1];
                
            //     writer.println("INSERT INTO account_favourite_hts (account_id, hts_code)");
            //     writer.println("SELECT " + accountId + ", '" + htsCode + "' FROM DUAL");
            //     writer.println("WHERE NOT EXISTS (");
            //     writer.println("    SELECT 1 FROM account_favourite_hts");
            //     writer.println("    WHERE account_id = " + accountId + " AND hts_code = '" + htsCode + "'");
            //     writer.println(");");
            //     writer.println();
            // }
            
            // ========== SEED HISTORICAL QUERIES ==========
            writer.println("-- ========== Historical User Queries ==========");
            writer.println("-- Past tariff queries made by users for analytics (world map + line graph)");
            writer.println("-- Note: Query entity has @ManyToOne relationship with Account");
            writer.println("-- The foreign key column name is 'userID' (mapped from Account entity)");
            writer.println();
            
            // Define historical queries: hts_code, transport_mode (might need to be removed i think), origin, quantity, userid
            // 
            String[][] queries = {
                // comparing historical prices (multiple query for same htscode)
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},
                {"1806.90.55.00", "SEA", "CHINA", "100", "1"},

                // one of each hts code --> sugar, bread, milk, egg, rice

                // egg
                {"0408.11.0000", "AIR", "NZ", "60", "1"},
                {"0408.19.0000", "AIR", "JP", "50", "2"},
                {"0408.91.0000", "SEA", "KW", "200", "2"},
                {"0408.99.0000", "SEA", "KR", "500", "2"},

                // rice
                {"1006.10.0000", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.2010", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.2090", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.4025", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.4035", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.4040", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.4060", "AIR", "TAIWAN", "75", "1"},
                {"1006.20.4080", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.1020", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.1040", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.9015", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.9057", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.9059", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.9061", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.9065", "AIR", "TAIWAN", "75", "1"},
                {"1006.30.9075", "AIR", "TAIWAN", "75", "1"},
                {"1006.40.0000", "AIR", "TAIWAN", "75", "1"},

                // milk (not concentrated 0401)
                {"0401.10.0000", "AIR", "TAIWAN", "75", "2"},
                {"0401.20.2000", "AIR", "TAIWAN", "75", "2"},
                {"0401.20.4000", "AIR", "TAIWAN", "75", "2"},
                {"0401.40.0200", "AIR", "TAIWAN", "75", "2"},
                {"0401.40.0500", "AIR", "TAIWAN", "75", "2"},
                {"0401.40.2500", "AIR", "TAIWAN", "75", "3"},
                {"0401.50.0200", "AIR", "TAIWAN", "75", "3"},
                {"0401.50.0500", "AIR", "TAIWAN", "75", "3"},
                {"0401.50.2500", "AIR", "TAIWAN", "75", "3"},
                {"0401.50.4200", "AIR", "TAIWAN", "75", "3"},
                {"0401.50.5000", "AIR", "TAIWAN", "75", "4"},
                {"0401.50.7500", "AIR", "TAIWAN", "75", "4"},

                // milk (concentrated 0402)
                {"0402.10.0500", "AIR", "TAIWAN", "75", "4"},
                {"0402.10.1000", "AIR", "TAIWAN", "75", "4"},
                {"0402.10.1050", "AIR", "TAIWAN", "75", "4"},
                {"0402.21.0200", "AIR", "TAIWAN", "75", "4"},
                {"0402.21.0500", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.2500", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.2700", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.3000", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.5000", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.7300", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.7500", "AIR", "TAIWAN", "75", "5"},
                {"0402.21.9000", "AIR", "TAIWAN", "75", "5"},
                {"0402.29.0500", "AIR", "TAIWAN", "75", "5"},
                {"0402.29.1000", "AIR", "TAIWAN", "75", "5"},
                {"0402.29.5000", "AIR", "TAIWAN", "75", "5"},
                {"0402.91.0300", "AIR", "TAIWAN", "75", "5"},
                {"0402.91.0600", "AIR", "TAIWAN", "75", "5"},
                {"0402.91.1000", "AIR", "TAIWAN", "75", "5"},
                {"0402.91.3000", "AIR", "TAIWAN", "75", "6"},
                {"0402.91.7000", "AIR", "TAIWAN", "75", "6"},
                {"0402.91.9000", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.0300", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.0600", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.1000", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.3000", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.4500", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.5500", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.6800", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.7000", "AIR", "TAIWAN", "75", "6"},
                {"0402.99.9000", "AIR", "TAIWAN", "75", "6"},

                // bread
                {"1905.10.0000", "AIR", "TAIWAN", "75", "1"},
                {"1905.20.0000", "AIR", "TAIWAN", "75", "1"},
                {"1905.31.0021", "AIR", "TAIWAN", "75", "1"},
                {"1905.31.0029", "AIR", "TAIWAN", "75", "1"},
                {"1905.31.0041", "AIR", "TAIWAN", "75", "2"},
                {"1905.31.0049", "AIR", "TAIWAN", "75", "2"},
                {"1905.32.0021", "AIR", "TAIWAN", "75", "2"},
                {"1905.32.0029", "AIR", "TAIWAN", "75", "2"},
                {"1905.32.0041", "AIR", "TAIWAN", "75", "2"},
                {"1905.32.0049", "AIR", "TAIWAN", "75", "2"},
                {"1905.40.0000", "AIR", "TAIWAN", "75", "2"},
                {"1905.90.1041", "AIR", "TAIWAN", "75", "2"},
                {"1905.90.1049", "AIR", "TAIWAN", "75", "2"},
                {"1905.90.1050", "AIR", "TAIWAN", "75", "2"},
                {"1905.90.1070", "AIR", "TAIWAN", "75", "2"},
                {"1905.90.1090", "AIR", "TAIWAN", "75", "2"},
                {"1905.90.9030", "AIR", "TAIWAN", "75", "3"},
                {"1905.90.9060", "AIR", "TAIWAN", "75", "3"},
                {"1905.90.9090", "AIR", "TAIWAN", "75", "3"},

                // sugar
                {"2303.20.0000s", "AIR", "TAIWAN", "75", "1"},

                
                // honey

            };
            
            for (String[] query : queries) {
                String htsCode = query[0];
                String modeOfTransport = query[1];
                String originCountry = query[2];
                String quantity = query[3];
                String userId = query[4];
                
                // No idempotency check for queries - historical records can have duplicates
                // (same user can query same product multiple times)
                // Column name is 'userID' (not 'userid') to match JPA @JoinColumn mapping
                writer.println("INSERT INTO query (hts_code, mode_of_transport, origin_country, quantity, userID)");
                writer.println("VALUES ('" + htsCode + "', '" + modeOfTransport + "', '" + originCountry + "', " + quantity + ", " + userId + ");");
                writer.println();
            }
            
            writer.println("-- Seed data generation complete");
            
            System.out.println("✓ Successfully generated seed-data.sql");
            System.out.println("✓ File location: backend/seed-data.sql");
            System.out.println("✓ Passwords have been BCrypt-hashed (cost factor: 10)");
            System.out.println();
            System.out.println("Next steps:");
            System.out.println("1. Review the generated seed-data.sql file");
            System.out.println("2. Ensure init.sql includes seed-data.sql (or append its contents)");
            System.out.println("3. Run: docker compose down -v");
            System.out.println("4. Run: docker compose up --build");
            System.out.println("5. Verify data: docker exec -it TarrificDB-mysql mysql -u sa -D TarrificDB -e \"SELECT * FROM account;\"");
            
        } catch (IOException e) {
            System.err.println("✗ Error generating seed-data.sql: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
