### Test US HTS REST API search endpoint

# Search for tariff articles containing the word "petroleum"
# GET http://localhost:8080/api/tariffs/search?keyword=sugar


# idk



# Search for tariff articles containing the word "sugar" and compare countries
GET http://localhost:8080/api/tariffs/countries?htsno=0401.20.40.00

Accept: application/json

###
GET http://localhost:8080/api/tariffs/most-queried
Accept: application/json

###
GET http://localhost:8080/api/tariffs/search?keyword=1704
Accept: application/json

###
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "username": "restuser2",
  "password": "P@ssw0rd",
  "email": "restuser2@gmail.com"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "restuser2",
  "password": "P@ssw0rd"
}

###
GET http://localhost:8080/logout
Content-Type: application/json


### 
PUT http://localhost:8080/accounts/15
Content-Type: application/json

{
  "userID": 15,
  "username": "restuser15",
  "email": "restuser3@gmail.com"
}

###
GET http://localhost:8080/product/category/search/sugar
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjc2Qtc2VjdXJpdHktYXBwIiwic3ViIjoicmVzdHVzZXIyIiwiZXhwIjoxNzYyNDI1NDYxLCJpYXQiOjE3NjIzMzkwNjEsInNjb3BlIjoiUk9MRV9VU0VSIn0.0A6CJj40LqqqM4Q2nv2p93_Na-rlByBJYp7v6eNMkoZtyS9gnHlcMJ0hISr61Cv01G45kHv8jRY33_Ss1cfSTA

###
GET http://localhost:8080/product/category/1209
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJjc2Qtc2VjdXJpdHktYXBwIiwic3ViIjoicmVzdHVzZXIyIiwiZXhwIjoxNzYyNDI1NDYxLCJpYXQiOjE3NjIzMzkwNjEsInNjb3BlIjoiUk9MRV9VU0VSIn0.0A6CJj40LqqqM4Q2nv2p93_Na-rlByBJYp7v6eNMkoZtyS9gnHlcMJ0hISr61Cv01G45kHv8jRY33_Ss1cfSTA